# A generic, single database database.

# version path separation is slightly different from the default,
# so that version paths can be displayed in the terminal with
# correct line breaks.

[alembic]
script_location = alembic
file_template = %%(year)d%%(month).2d%%(day).2d_%%(rev)s_%%(slug)s
prepend_sys_path = src
output_encoding = utf-8
sqlalchemy.url = postgresql+psycopg://%(DATABASE_URL)s

# Template used to generate migration file names
# The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with
# date and time
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(rev)s_%%(slug)s

# sys_path found in this folder and its subdirectories.
# See the docs for details on how to use this setting.

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If left unspecified, the local timezone will be used.
# timezone =

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .hclconfig files in the migration
# directory to configure the environment.
# hclconfig_environment = false

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
